# PARA RENDER
version: "3.9"

services:
  ads-coworking-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coworking_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SPRING_DATASOURCE_DB_HOST}:${DB_PORT}/${SPRING_DATASOURCE_DB_NAME}?sslmode=require
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    env_file:
      - .env
    depends_on: []

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: coworking_front
  #   ports:
  #     - "4200:80"
  #   depends_on:
  #     - ads-coworking-app