# Build stage
FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

# Serve stage
FROM nginx:1.23-alpine
COPY --from=build /app/dist/mini-booking /usr/share/nginx/html
EXPOSE 80
